name: Cross Platform Release Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          #- os: ubuntu-latest
          #  platform: linux
          #  arch: x86_64
          #  ext: ""
          - os: windows-latest
            platform: windows
            arch: x86_64
            ext: ".exe"
          #- os: macos-latest
          #  platform: macos
          #  arch: arm64
          #  ext: ""

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.platform }}-${{ matrix.arch }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache VCPKG
      uses: actions/cache@v4
      with:
        path: |
          vcpkg/buildtrees
          vcpkg/installed
          vcpkg/packages
          vcpkg_installed
          build
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Setup CMake & Ninja
      uses: lukka/get-cmake@latest
      with:
        useLocalCache: false
        useCloudCache: false

    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11

    - name: Build
      run: python3 scripts build

    - name: Package
      run: python3 scripts package

    - name: Pre-Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type != 'tag'
      with:
        tag_name: build-${{ github.run_number }}
        prerelease: true
        files: |
          build/telebot-${{ matrix.platform }}-${{ matrix.arch }}.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          build/telebot-${{ matrix.platform }}-${{ matrix.arch }}.zip
