name: Cross Platform Release Build

on:
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            ext: ""
          - os: windows-latest
            platform: windows
            arch: x86_64
            ext: ".exe"
          - os: macos-latest
            platform: macos
            arch: arm64
            ext: ""

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.platform }}-${{ matrix.arch }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check toolchain
      run: |
        echo "Platform: ${{ matrix.platform }}-${{ matrix.arch }}"
        echo "GCC: "
        gcc --version

        echo "G++: "
        g++ --version

        echo "Python3: "
        python3 --version

        echo "CMake: "
        cmake --version

        echo "Ninja: "
        ninja --version

        echo "VCPKG: "
        vcpkg --version
      shell: bash
