name: Cross Platform Release Build

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          #- os: ubuntu-latest
          #  platform: linux
          #  arch: x86_64
          #  ext: ""
          - os: windows-latest
            platform: windows
            arch: x86_64
            ext: ".exe"
            vcpkg_triplet: x64-windows-release
          #- os: macos-latest
          #  platform: macos
          #  arch: arm64
          #  ext: ""

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.platform }}-${{ matrix.arch }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup CMake & Ninja
      uses: lukka/get-cmake@latest

    - name: Setup VCPKG & install
      uses: lukka/run-vcpkg@v11
      with:
        runVcpkgInstall: true
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Environment Variables
      run: |
        echo "VCPKG_ROOT=$VCPKG_ROOT"
      shell: bash

    - name: Build
      run: python3 scripts build
      shell: bash

    #- name: Package
    #  run: |
    #    mkdir -p package
    #    cp build/telebot${{ matrix.ext }} package/
    #    
    #    if [ "${{ matrix.platform }}" = "windows" ]; then
    #      powershell -Command "Compress-Archive -Path package\\* -DestinationPath ${{ matrix.platform }}-${{ matrix.arch }}.zip"
    #    else
    #      zip -r ${{ matrix.platform }}-${{ matrix.arch }}.zip package
    #    fi
    #  shell: bash

    #- name: Upload
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    files: ${{ matrix.platform }}-${{ matrix.arch }}.zip
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
