name: Cross Platform Release Build

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            ext: ""
          - os: windows-latest
            platform: windows
            arch: x86_64
            ext: ".exe"
          - os: macos-latest
            platform: macos
            arch: arm64
            ext: ""

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.platform }}-${{ matrix.arch }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install VCPKG
      if: runner.os == 'macOS'
      run: brew install vcpkg

    - name: Check toolchain
      run: |
        echo "Platform: ${{ matrix.platform }}-${{ matrix.arch }}"
        echo "GCC: "
        gcc --version

        echo "G++: "
        g++ --version

        echo "Python3: "
        python3 --version

        echo "CMake: "
        cmake --version

        echo "Ninja: "
        ninja --version

        echo "VCPKG: "
        vcpkg --version

        echo "VCPKG_ROOT: $VCPKG_ROOT"
      shell: bash

    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: CMakeLists.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
